services:
  evolution:
    image: 'evoapicloud/evolution-api:latest'
    container_name: '${PREFIXO_CONTAINER}_evolution'
    networks:
      instancia_net:
        ipv4_address: ${IP_EVOLUTION}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '${CPU_EVOLUTION:-1.0}'
          memory: '${MEM_EVOLUTION:-1024M}'
        reservations:
          memory: '${RES_EVOLUTION:-256M}'
    environment:
      - TZ=America/Sao_Paulo
      - NODE_OPTIONS=--max-old-space-size=${NODE_HEAP_DEFAULT:-768} --no-deprecation
      - EVOLUTION_OPERATOR_EMAIL=${TS_EMAIL}
      - SERVER_NAME=${PREFIXO_CONTAINER}_evolution
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=${SERVER_URL}
      - TELEMETRY_ENABLED=false
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR,WARN
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - EVENT_EMITTER_MAX_LISTENERS=50
      - CONFIG_SESSION_PHONE_CLIENT=${PREFIXO_CONTAINER}
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#175197
      - DEL_INSTANCE=false
      - SWAGGER_ENABLED=true
      - DOCS_ENABLED=true
      - WEBSOCKET_ENABLED=false
      - LANGUAGE=pt-BR
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/evolution_db?schema=public
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/evolution_db?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=${PREFIXO_CONTAINER}_evolution
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_SAVE_IS_ON_WHATSAPP=true
      - DATABASE_SAVE_IS_ON_WHATSAPP_DAYS=7
      - DATABASE_DELETE_MESSAGE=true
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://${IP_REDIS}:6379/0
      - CACHE_REDIS_PREFIX_KEY=${PREFIXO_CONTAINER}_evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      - S3_ENABLED=${EVOLUTION_S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY_ID:-${TS_EMAIL}}
      - S3_SECRET_KEY=${S3_SECRET_ACCESS_KEY:-${DB_PASSWORD}}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-${TS_EMAIL}}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-${DB_PASSWORD}}
      - S3_BUCKET=${S3_EVOLUTION_BUCKET:-evolution}
      - S3_PORT=${S3_PORT:-9000}
      - S3_ENDPOINT=${TS_DOMAIN:-s3minio}
      - S3_USE_SSL=${S3_USE_SSL:-false}
      - S3_REGION=us-east-1
      - CHATWOOT_ENABLED=true
      - CHATWOOT_MESSAGE_READ=true
      - CHATWOOT_MESSAGE_DELETE=true
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${PREFIXO_CONTAINER}_db?sslmode=disable
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=true
    extra_hosts:
      - "${TS_DOMAIN:-localhost}:${IP_S3MINIO}"
    volumes:
      - './volumes/evolution_instances:/evolution/instances'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/ || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s

  caddy:
    ports:
      - "${HOST_EVO_PORT:-18081}:18081/tcp"
